### ISSUE TITLE
Unable to select target for countermeasures/unable to import models

### ISSUE THREAD

**Issue by LukeLaboosh** [cairis-platform/cairis#634]
### Expected behaviour
I have created threats threats and requirements and should be able to fully write the counter measures by selecting the associated requirement and threat.
Also I have created backups of my Cairis which I should be able to import.

### Actual behaviour
When attempting to create a counter measure no targets come up. everything else seems to function as expected
I also cannot import the model after exporting it.

### Steps to reproduce the behaviour
Create new counter measure. Name, requirement, description etc.
Add requirement.
Should be able to add target.

also:
export as model.cairis
should be able to import model.cairis

### Version of CAIRIS
Cairis.2.3.8

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Windows
Chrome Version 95.0.4638.69 and firefox
[SBD not working.zip](https://github.com/cairis-platform/cairis/files/7512345/SBD.not.working.zip)
![image](https://user-images.githubusercontent.com/70753897/141107466-a89fc531-a48e-4eeb-bd3e-75b775e10efe.png)

**Comment by failys** [comment]
There are a few reasons why this is happening.  
First, to view targets then you need to add a KAOS association such that the sub-goal is your requirement, and the goal is either linked to your risk response, or a refinement to a goal that is.  In your model, the requirement isn't linked to anything, which is why you aren't getting any targets (as CAIRIS doesn't see the requirement as linked to any risks).
Second, it's important that the 'Prevent' goal is generated by CAIRIS not simply created by hand.  This is because CAIRIS adds a link between the response and the goal before the sub-goals (associated with the threat and vulnerability are created).  In your model, it looks like you created all these goals by hand.

I suggest deleting your prevent goals, generating the goals again from the response, and then adding the missing KAOS association as mentioned above. Once the requirement in your countermeasure is linked back to your risks then you should see your targets.
