### ISSUE TITLE
Vagrant / Virtualbox unable to start on M1

### ISSUE THREAD

**Issue by lucasgonze** [cairis-platform/cairis#654]
### Expected behaviour

`vagrant up` works

### Actual behaviour

`vagrant up` throws 

```
Result Code: | NS_ERROR_FAILURE (0x80004005)
Component: | MachineWrap
Interface: | IMachine {85632c68-b5bb-4316-a900-5eb28d3413df}

```
### Steps to reproduce the behaviour

```
git clone https://github.com/cairis-platform/cairis
vagrant up
M1-Air-2086:cairis lucasgonze$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'bento/ubuntu-20.04'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/ubuntu-20.04' version '202206.03.0' is up to date...
==> default: Setting the name of the VM: cairis_default_1663207263640_70479
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 7071 (guest) => 7071 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "b99dbcdb-342a-466a-a5a0-2d0779b8f1ea", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'cairis_default_1663207263640_70479' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
```

### Version of CARIS

`git clone https://github.com/cairis-platform/cairis` on Sep 14 2022

### Details of browser or, if applicable, details of the OS used to host CAIRIS

MacBook Air (M1, 2020)

**Comment by failys** [comment]
Sounds like an issue with Vagrant rather than CAIRIS, although I've seen this sort of thing before if VirtualBox or Vagrant is out of date.  Try doing a `vagrant destroy`, removing the cloned repo, checking you have the latest version of vagrant, before re-cloning the repo and trying again.
I'm also assuming the Vagrant/VirtualBox works on MacBook Airs.  If you have other VMs that work on your laptop then it's fine. If not, it's worth checking for possible hardware compatibility issues.  If supportability is in question  then you might want to try running CAIRIS on Docker instead.

**Comment by failys** [comment]
I've just checked the Vagrant setup on my own Mac, and everything seems to work ok.

**Comment by lucasgonze** [comment]
I think the issue is that VirtualBox does not exist for the M1 chip. Does your mac have an Intel chip?

**Comment by lucasgonze** [comment]
I'm out.
