### ISSUE TITLE
CAIRIS Demo

### ISSUE THREAD

**Issue by kay07949** [cairis-platform/cairis#661]
I need to do a presentation of CAIRIS tomorrow, however i cannot access the demo environment, each time i try to log in it says:

"
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
"

**Comment by failys** [comment]
It should be available again now.

**Comment by kay07949** [comment]
same error, this is not working. I've tried different browsers too.

**Comment by kay07949** [comment]
doesn't allow me to log in and when i click on register or reset, gives me the error:

"
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
"

**Comment by failys** [comment]
I've just logged into the live demo as test@test.com and everything is ok.  There is another problem registering for accounts on the live demo.  Based on the error, that seems to be the problem you're having rather than logging in with an account that already exists.  That's under investigation as another issue.

**Comment by kay07949** [comment]
I cant login with the account I registered with, and I am certain I am entering the correct password.

**Comment by failys** [comment]
There is only one account on the live demo : test@test.com.  The weekly rebuild was run today to ensure the latest CAIRIS container was running.  Hopefully, you have a backup of whatever you were working on.

**Comment by kay07949** [comment]
can I log in with the test@test.com? I still cant access the demo with the account I registered and it doesn't allow me to register a new account. It gives the same error: "Internal Server Error..."

**Comment by failys** [comment]
The account you registered with would have been removed.  All accounts are removed every week but, because of the problems we've been investigating, all the accounts were removed when we rebuilt everything.

I've just logged into the live demo as test@test.com and created a new account.  I didn't get any problems with either.
