### ISSUE TITLE
Unable to register for Cairis demo

### ISSUE THREAD

**Issue by TheComamba** [cairis-platform/cairis#670]
### Expected behaviour
I am able to create a user account.

### Actual behaviour
I tried to register on [https://demo.cairis.org/register](https://demo.cairis.org/register), but encountered a Code 500 internal server error.
I checked if the credentials got transmitted by trying them on [https://demo.cairis.org/login](https://demo.cairis.org/login), but hitting the login button only reloaded the page.
The Browser console shows the Code 500 Error in the first case, but nothing more.

### Steps to reproduce the behaviour
Go to the Websites and try registering or logging in.

### Version of CAIRIS
Never got that far. :(

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Tested in Microsoft Edge Version 118.0.2088.69 (Official Build) (64-Bit) and Firefox 115.3.1esr (64-bit).

**Comment by failys** [comment]
This looks a problem specific to the live demo rather than CAIRIS itself.  It's possible to create user accounts on the server itself, but account registration is failing due to problems on the email server used by the live demo.  I'm having problems accessing that email server, so it could be a while until this issue is resolved.  In the meantime, I suggest you either (i) use the test@test.com account, (ii) contact me directly and I can create an account on the server for you.

**Comment by TheComamba** [comment]
Thanks a lot, test@test.com is absolutely sufficient to get a first look at the tool.

**Comment by failys** [comment]
This is an issue with the configuration of CAIRIS re: the live demo, not with CAIRIS per se
